version: '3'

tasks:
  build-ledmatrix:
    cmds:
      - go build -x

  build-librgbmatrix:
    cmds:
      - cd {{.USER_WORKING_DIR}}/../lib && make clean
      - cd {{.USER_WORKING_DIR}}/../lib && make all
      - cd {{.USER_WORKING_DIR}}/../lib && cp ./librgbmatrix.* {{.USER_WORKING_DIR}}
